config/routes.rb
Rails.application.routes.draw do
  
  # required for devise
  root to: 'static#home'
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :gratitudes do
    resources :comments
  end
  post '/gratitudes/:id/edit' => 'gratitudes#edit'
  
  resources :comments

  resources :users do
    resources :gratitudes, only: [:new, :create, :index] #shallow routes: only nest the routes you need (crucial to know the post_id)
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  #scope method requirement
  scope :ordered_by_title, -> { order(title: :asc) }
  scope :ordered_by_time, -> { order(created_at: :desc) }
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gratitude

    validates :content, presence: true
end

app/models/gratitude.rb
class Gratitude < ApplicationRecord
    
  belongs_to :user
  has_many :comments
  has_many :users, through: :comments
  validates :content, presence: true
  validates :title, presence: true


end

app/models/user.rb
class User < ApplicationRecord

  has_many :gratitudes
  has_many :comments

  # need to source this relationship with the join table
  has_many :commented_gratitudes, through: :comments, source: :gratitude

  validates :email, presence: true


  # Include default devise modules. Others available are:
  # :confirmable(email to confirm who you are), :lockable(lock users if they fail too much to sign in), :timeoutable(allow users to sign out after a certain amount of time), 
  # :trackable(keep a log od when users log in and out) and :omniauthable(log in with google, etc)
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
      
    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(email: data['email'],
          password: Devise.friendly_token[0,20]
          )
      end
      user  
    end         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    def index
        #need to check if it's nested
        if params[:gratitude_id] && @gratitude = Gratitude.find_by_id(params[:gratitude_id])
            @comments = @gratitude.comments
        else
            @error = "That gratitude doesn't exist!" if params[:gratitude_id]
            @comments = Comment.all.ordered_by_time
        end
    end

    def new
        #if nested and we find the post
        if params[:gratitude_id] && @gratitude = Gratitude.find_by_id(params[:gratitude_id])
            #use the join table associations
            @comment = @gratitude.comments.build
        else
            @error = "That gratitude doesn't exist!" if params[:gratitude_id]
            @comment = Comment.new
        end
    end

    def create
        #build doesn't save to database, but returns a new object of the associated type to be used in the view 
        @comment = current_user.comments.build(comment_params)
        if @comment.save
            flash[:message] = "Comment created!"
            redirect_to gratitude_comments_path
        else
            render :new
        end
    end

    def destroy
        @comment = Comment.find_by(id: params[:id])
        @comment.destroy
        flash[:notice] = "Comment deleted!"
        redirect_to recipe_path(@comment)
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :gratitude_id)
    end
end

app/controllers/gratitudes_controller.rb
class GratitudesController < ApplicationController
    def new
        @gratitude = Gratitude.new
    end

    def create
        #build doesn't save to database, but returns a new object of the associated type to be used in the view 
        @gratitude = current_user.gratitudes.build(gratitude_params)
        if @gratitude.save
            flash[:message] = "Gratitude created!"
            redirect_to gratitudes_path
        else
            @error = "Fill in your gratitude!"
            render :new
        end
    end

    def show
        @gratitude = Gratitude.find_by_id(params[:id])
        redirect_to gratitudes_path if !@gratitude
    end

    def index
        @gratitudes = Gratitude.all.ordered_by_time
    end

    def edit
        @gratitude = Gratitude.find_by_id(params[:id])
        if !@gratitude || @gratitude.user != current_user
            flash[:message] = "You aren't allowed to do that!"
            redirect_to gratitudes_path 
        end
    end
    
    def update
        @gratitude = Gratitude.find_by_id(params[:id])
        #authenticates the user and gratitude, redirects if false
        if !@gratitude || @gratitude.user != current_user
            flash[:message] = "You aren't allowed to do that!"
            redirect_to gratitudes_path 
        elsif @gratitude.update(gratitude_params)
            redirect_to gratitude_path(@gratitude)
        else
            render :edit
        end
    end

    def destroy
        @gratitude = Gratitude.find_by(id: params[:id])
        if @gratitude.user != current_user
            flash[:message] = "You aren't allowed to do that!"
            redirect_to gratitudes_path 
        else
            @gratitude.destroy
            flash[:notice] = "Gratitude deleted!"
            redirect_to gratitude_path(@gratitude)
        end
    end

    def longest_content_g
        @gratitudes = Gratitude.all.longest_content
    end

    private

    def gratitude_params
        params.require(:gratitude).permit(:title, :content)
    end

    def if_current_user_and_gratitude

    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    # permits all the attributes we want, for example if we wanted name or username (we put it in as an argument)
    def sign_up_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
     
      def account_update_params
        params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
      end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_user!
    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end

        #through devise - ***if a user is not logged in, can't see another user's show page and redirects to the login page***


    #for User show page
    def show
        user_signed_in? #devise helper method
                  # .find will break and throw an error.. would need a rescue statement
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gratitudes_helper.rb
module GratitudesHelper
end

app/views/comments/index.html.erb
<% if @gratitude %>
  <h1>Comments for <%= @gratitude.title%></h1>
<% else %>
  <h1>All Comments</h1>
<% end %>

<ul>
<% @comments.each do |c|%>
  <li><%= c.user.email%> says "<%= c.content%>" about this gratitude: <strong><%= link_to c.gratitude.title, gratitude_path(c.gratitude_id) %></strong></li>
  <br>
<% end %>
</ul>

app/views/comments/new.html.erb
<% if @gratitude %>
<h1>Add a new comment for <%=@gratitude.user.email%>'s gratitude!</h1>
<h4>What they're grateful for:</h4>
<p><%= @gratitude.content %></p>
<% else %>
<h1>Add a new comment!</h1>
<% end %>

<%= render partial: "layouts/error", locals: {object: @comment} %>

<%= form_for([@comment.gratitude, @comment]) do |f|%>

    <% if !@comment.gratitude %>
        <%= f.label :gratitude %>
        <%= f.collection_select :gratitude_id, Gratitude.all, :id, :title %>
    <% else %>
        <%= f.hidden_field :gratitude_id %>
    <% end %>

        <%= f.label "Say something nice!" %>
        <%= f.text_field :content, size: "60x50" %>

        <%= f.submit "Submit" %>
    <% end %>
 

app/views/gratitudes/edit.html.erb
<h1> <center> Edit <%=@gratitude.title%>! </center> </h1>
<br><br>
    <h3>
        <center>
            <%= form_for(@gratitude) do |grat| %>
                <%= Time.now.strftime("%A %m/%d/%Y %r") %>
                    <br><br>
                <%= grat.text_field :title, placeholder: "Your title...", size: "40x30" %>
                    <br><br>
                <%= grat.text_area :content, placeholder: "Write 3 things your grateful for!", size: "55x15" %>
                    <br><br>
                <%= grat.submit %>
            <% end %>
        </center>
    </h3>

app/views/gratitudes/index.html.erb
<h1>All Gratitudes</h1>

<ul>
  <% @gratitudes.each do |grat| %>
    <li><%= link_to grat.title, gratitude_path(grat) %> by <%= grat.user.email %> on <%= grat.created_at.strftime("%A %m/%d/%Y %r") %> </li>
    <br>
  <% end %> 
</ul>

app/views/gratitudes/new.html.erb
<h1> <center> Create your Gratitudes! </center> </h1>
<br><br>

<%= render partial: "layouts/error", locals: {object: @gratitude} %>

<br>

    <h3>
        <center>
            <%= form_for(@gratitude) do |grat| %>
                <%= Time.now.strftime("%A %m/%d/%Y %r") %>
                    <br><br>
                <%= grat.text_field :title, placeholder: "How was your day?", size: "40x30" %>
                    <br><br>
                <%= grat.text_area :content, placeholder: "Write 3 things your grateful for!", size: "55x15" %>
                    <br><br>
                <%= grat.submit %>
            <% end %>
        </center>
    </h3>

app/views/gratitudes/show.html.erb
<h1><center> <%= @gratitude.title %> </center></h1>
<center><p>Created on <%= @gratitude.created_at.strftime("%A %m/%d/%Y %r") %> </p></center>

<center><%= @gratitude.content %></p></center>
<br>
  <%= button_to "Edit", edit_gratitude_path(@gratitude)%>
  <%= button_to "Delete", gratitude_path(@gratitude), method: 'delete' %>

<h3>Comments</h3>
<p><%= link_to "Add a comment", new_gratitude_comment_path(@gratitude) %> </p>

  <% @gratitude.comments.order(updated_at: :desc).limit(3).each do |c|%>
      "<%= c.content %>" 
      <br>
      at <%=c.updated_at.strftime("%I:%M %p on %m/%d/%Y")%> by <strong><%= c.user.email%></strong>
      <br><br>
  <% end %>

<p> <%= link_to "See All Comments", gratitude_comments_path(@gratitude) %></p>

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="nav">
    <ul>
        <% if !user_signed_in? %>
            <%= link_to "Log In", new_user_session_path %>
                <br>
            <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>
                <br>    
            <%= link_to "Sign Up", new_user_registration_path  %>
        <% end %>
        <br>
        <% if user_signed_in? %>
            <%= link_to "Home", "/" %> |
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>  |  
            <%= link_to "All Gratitudes", gratitudes_path %> | 
            <%= link_to "Create Gratitudes", new_gratitude_path %>

        <% end %>
        <br>    
    </ul> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGratitudeJournal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render 'layouts/nav' %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      <div>
        <% if flash[:message] %>
          <%= flash[:message]  %>
        <% end %>
      </div>

       <p><%= @error %></p>

    <%= yield %>
    
  </body>
</html>